### ISSUE TITLE
Using AWS4

### ISSUE THREAD

**Issue by ameer-jabbar** [ceph/s3-tests#151]
What's the proper way to invoke the AWS4 authentication path with s3-tests? I looked through some old issues and found one that indicating something like this to try:

`S3TEST_CONF=aws.conf S3_USE_SIGV4=1 nosetests s3tests.functional.test_s3:test_object_raw_get_x_amz_expires_not_expired -a 'auth_aws4'`

I also tried

`S3TEST_CONF=aws.conf S3_USE_SIGV4=true nosetests s3tests.functional.test_s3:test_object_raw_get_x_amz_expires_not_expired -a 'auth_aws4'`

But neither resulted in AWS4 authentication headers. So, I was wondering what the proper way to do it. BTW, I have boto version 2.6.0 in my environment.

Thanks.

**Comment by yehudasa** [comment]
@ameer-jabbar I run it like this:
S3_USE_SIGV4=1 S3TEST_CONF=s3tests.conf virtualenv/bin/nosetests s3tests -v -a '!fails_on_rgw' -a auth_aws4 

It works for me on a much newer boto version (2.39).
