### ISSUE TITLE
Does AWS S3 support conditional put?

### ISSUE THREAD

**Issue by kevin-wyx** [ceph/s3-tests#218]
I am testing OpenStack Swift using s3-tests, all cases about conditional put/update output FAIL/ERROR.

Like: `s3tests.functional.test_s3.test_put_object_ifmatch_good`

Then I test conditional put with AWS S3, it raises NotImplemented error.

```
./s3curl/s3curl.pl --id test  --   http://testbucket.s3-ap-southeast-1.amazonaws.com/aaa -X PUT  --data @/tmp/aaa  -H 'If-Match: abc'
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Header>If-Match</Header><RequestId>301498F0A024E98Q</RequestId><HostId>Yd9JPz7BG8ixUiSCtVOSl90fGjqNtxH45WJa0hb+bli6x88TNjyxhzVFxRI6CHjHDA6GR8cIE8Y=</HostId></Error>
````

Does S3 not actually support conditional put?

**Comment by gaul** [comment]
Conditional PUT is a Ceph extension.  AWS S3 cannot support this due to eventually consistency.

**Comment by kevin-wyx** [comment]
Thanks, @gaul.
