### ISSUE TITLE
ceph 12.2.5 FAILED (SKIP=85, errors=25, failures=17)  is ok?

### ISSUE THREAD

**Issue by a523** [ceph/s3-tests#231]
I used this script to test ceph 12.2.5 and the result is "FAILED (SKIP=85, errors=25, failures=17)"
Is the result correct?
Shouldn't ceph pass 100%?

**Comment by a523** [comment]
now ,find err one

**Comment by AlexBaranowski** [comment]
Hi,

I have quite a similar problem. Did you find a bug? Or is the high number of errors and failures expected?
