### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by yeliazar** [ceph/s3-tests#274]
I'm trying to run the tests with self-signed certificate and almost every tests fails with error:
`SSL: CERTIFICATE_VERIFY_FAILED`

is_secure is set to 'True' in config file. 

Is there any way to ignore SSL certificate error?

**Comment by yeliazar** [comment]
I replaced
`"self._setup_ssl_cert(conn, request.url, self._verify)" `
with 
`"self._setup_ssl_cert(conn, request.url, False)"`
in virtualenv/lib/python2.7/site-packages/botocore/httpsession.py
but I still getting 'Access denied" error during `s3.ListBuckets` operation

**Comment by AlexBaranowski** [comment]
Can you try it with changed /etc/python/cert-verification.cfg?
Does setting PYTHONHTTPSVERIFY helps?
You can try something like this:
```
PYTHONHTTPSVERIFY=0 S3TEST_CONF=my_s3_tests.conf ./virtualenv/bin/nosetests
```

**Comment by ticapix** [comment]
A colleague faced the same issue and solved it by adding the full certificate chain on the server.

**Comment by psathyan** [comment]
I am also hitting this issue however there is `1 fail` and `40 errors` in the result. Some details

- Using the branch `ceph-nautilus`
- Operating System `RHEL 8.3`
- RADOS GW
    - `rgw frontends = beast ssl_endpoint=x.x.x.x:443 ssl_certificate=<path_to_cert> ssl_private_key=<path_to_key>`
- Self signed certificate added to the node's CA store.
- `curl` responds without any error or warning
- using boto in custom script works

Troubleshooting steps taken
- `export PYTHONHTTPSVERIFY=0`
- `cert-verification.cfg` has `verify=disable` in the __https__ section. The file is stored in the folder `/opt/rh/python27/root/etc/python/cert-verification.cfg`

Error
```
raceback (most recent call last):
  File "/root/s3-venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/s3-tests/s3tests/functional/test_s3.py", line 1463, in test_post_object_anonymous_request
    r = requests.post(url, files = payload)
  File "/root/s3-venv/lib/python2.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/s3-venv/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/s3-venv/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/s3-venv/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/s3-venv/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='ceph-pragadee-1610251228563-node3-monrgw', port=443): Max retries exceeded with url: /cephuser-jhtvf9f8yl7yrpziimwg-1 (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
```
Please can anyone give me additional pointers that could help in resolving this issue?
