### ISSUE TITLE
Test suite broken under python 3.10+ (nose not maintained)

### ISSUE THREAD

**Issue by mpaulon** [ceph/s3-tests#483]
Running the s3-tests with `S3TEST_CONF=conf ./virtualenv/bin/nosetests` return the following traceback:
```
  File "/home/michael/git/s3flask/s3-tests/virtualenv/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```
`Callable` has been moved under `collections.abc` as of python 3.10.
There is the following [issue](https://github.com/nose-devs/nose/issues/1122) opened on the nose github, but the nose test framework has been unmaintained for several years and it looks like it wont be updated for python 3.10+.

**Comment by cbodley** [comment]
thanks @mpaulon. we had to use older python as a workaround for a long time, but this was finally resolved in https://github.com/ceph/s3-tests/pull/482
