### ISSUE TITLE
help: tox: error: unrecognized arguments

### ISSUE THREAD

**Issue by kungf** [ceph/s3-tests#512]
when I run `S3TEST_CONF=s3tests.conf.SAMPLE  tox s3tests_boto3/functional/test_s3.py::test_bucket_list_empty
` in mac, some errors happen:

usage: tox [-h] [--colored {yes,no}] [-v | -q] [--exit-and-dump-after seconds] [-c file] [--workdir dir] [--root dir] [--runner {virtualenv}] [--version] [--no-provision [REQ_JSON]] [--no-recreate-provision] [-r] [-x OVERRIDE]
           {run,r,run-parallel,p,depends,de,list,l,devenv,d,config,c,quickstart,q,exec,e,legacy,le} ...
tox: error: unrecognized arguments: s3tests_boto3/functional/test_s3.py::test_bucket_list_empty
hint: if you tried to pass arguments to a command use -- to separate them from tox ones

**Comment by kungf** [comment]
fix by change tox from v4.x to v3.28

**Comment by kaajii** [comment]
use like S3TEST_CONF=s3tests.conf.SAMPLE  tox -- s3tests_boto3/functional/test_s3.py::test_bucket_list_empty 

"--" separate arguments and command
