### ISSUE TITLE
way to know the list of successful tests?

### ISSUE THREAD

**Issue by akiradeveloper** [ceph/s3-tests#94]
Hi,

I am writing s3 compatible server-side and using s3-tests for its testing.

https://github.com/akiradeveloper/akashic-storage

At the moment, most of the tests fail and I can know from the log which tests failed.

```
Ran 420 tests in 37.363s

FAILED (SKIP=51, errors=127, failures=109)
```

I want to know which tests **succeeded**. How can I know this?

**Comment by theanalyst** [comment]
Since we run nosetests, setting the verbose flag `-v` or `-vv` etc. should do the trick?

**Comment by akiradeveloper** [comment]
@theanalyst  Oh works.
